version: '3'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres_tasks
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tasks
    ports:
      - '5432:5432'
    volumes:
      - tasks_postgres:/var/lib/postgresql/data
    networks:
      - tasks

volumes:
  tasks_postgres:                  

networks:
  tasks:
    driver: bridge